[package]
name = "qcker-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Qcker engine - image management and registry client"

[dependencies]
qcker-common = { path = "../qcker-common" }
qcker-ext-api = { path = "../qcker-ext-api" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
dirs = "5"
tar = { workspace = true }
flate2 = { workspace = true }
base64 = "0.21"
chrono = "0.4"
md5 = "0.7"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = { workspace = true }
